### ISSUE TITLE
KDE Fedora 36 needs 2 more dependencies

### ISSUE THREAD

**Issue by ejnshtein** [alex1701c/krunner-vscodeprojects#8]
I tried installing this module on my new Fedora 36-based system with KDE and got the following errors:
![image](https://user-images.githubusercontent.com/18352350/189538666-27689839-ce70-43d1-baba-f0c5e0e16b19.png)

And
![image](https://user-images.githubusercontent.com/18352350/189538701-23116c4c-941f-4c41-a221-4a18f0666c07.png)

After googling, the first issue was resolved by installing `qt5-qtdeclarative-devel` package and the second by installing `kf5-kconfigwidgets-devel` package.

If you can test and verify this in a VM and/or update dependencies section it will be great!

Thanks.

**Comment by alex1701c** [comment]
>After googling, the first issue was resolved by installing qt5-qtdeclarative-devel package

The KRunner dependencies are quite messy. I believe this package is needed, because KRunner depends on plasma-frameworks which depends on QDeclarative.

> and the second by installing kf5-kconfigwidgets-devel package.

Makes sense, this is used directly.

I have updated the list of dependencies in https://github.com/alex1701c/krunner-vscodeprojects/commit/9d562574815f91f47c9bebb24898ffc86beda5d2.
